image: Visual Studio 2019

platform:
- x86
- x64

configuration:
  - Debug
  - Release
  
matrix:
  fast_finish: true
  
install:
  - mkdir build
  - cd build

build_script:  
  - if %platform%==x86 set generator=Win32
  - if %platform%==x64 set generator=x64
  - echo Visual Studio 16 2019 -A %generator% %configuration%
  - cmake .. -G"Visual Studio 16 2019" -A %generator% -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=./output
  - cmake --build . --target INSTALL
  - 7z a vc140_%configuration%_%PLATFORM%.zip -i!%APPVEYOR_BUILD_FOLDER%\build\output\*
  - appveyor PushArtifact vc140_%configuration%_%PLATFORM%.zip
  
deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
